m1x: 0.0
m1y: -0.57728
m1z: 0.81654
m2x: 0.0
m2y: 0.81654
m2z: 0.57728
nv_depth: 20.0
proton_count: 4000
output_file: out_cli_try_2.h5
stl_file: HollowChip.stl
resolution_x: 500
resolution_y: 500
diffusion_coefficient: 0.004
frequency: 85
number_time_steps: 80
timestep: 0.00000001
parallelization_level: 10
